#!/usr/bin/env bash
# Configures localhost and facebook.com IP resolution in /etc/hosts

sed 's/127.0.0.1/127.0.0.2/' /etc/hosts > /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts